spring:

  application:
    name: microservice-task

  data:
    mongodb:
      database: ${MONGODB_DATABASE}
      uri: ${MONGODB_URI}

  h2:
    console:
      enabled: true

  artemis:
    mode: native
    broker-url: ${SPRING_ARTEMIS_BROKER_URL}
    user: ${SPRING_ARTEMIS_USER}
    password: ${SPRING_ARTEMIS_PASSWORD}
  
  jms:
    listener:
      auto-startup: ${JMS_ENABLED}

  datasource:
    url: jdbc:h2:mem:microdb
    driverClassName: org.h2.Driver
    username: username
    password: password

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 0

eureka:
  client:
    register-with-eureka: ${EUREKA_ENABLED}
    fetch-registry: ${EUREKA_ENABLED}
    enabled: ${EUREKA_ENABLED}
    serviceUrl:
      defaultZone: ${EUREKA_URI}

  instance:
    id: ${spring.application.name}:${random.value}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90

app:
  queue: Asynchronous.Task

logging:
  level:
    org.springframework.jms: INFO
    com.antonio.microservicestask: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level [%X{transactionId}] %logger{36} - %msg%n"